import Head from 'next/head'
import Header from '../components/Header/Header'
import SlickSwiper from '../components/Swiper/Swiper'
import ProductCard from '../components/ProductCard/ProductCard' 

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header/>
      <SlickSwiper/>
      <div style={{display:'flex', flexDirection:'row'}}>
      <ProductCard img='https://image.oppo.com/content/dam/oppo/common/mkt/v2-2/oppo-find-x3-series/middle-banner/find-x3-pro/Find%20X3-middlebanner-1600x1068-black-v2-pc.jpg'/>
      <ProductCard img='https://image.oppo.com/content/dam/oppo/common/mkt/v2-2/oppo-find-x3-series/middle-banner/find-x3-pro/Find%20X3-middlebanner-1600x1068-black-v2-pc.jpg'/>
      </div>
    </>

  )
}
